### ISSUE TITLE
Use 'namespace' instead of 'nameSpace'

### ISSUE THREAD

**Issue by pmorie** [gabemontero/openshift-jenkins-buildutils#1]
This plugin should use 'namespace' instead of 'nameSpace', since 'namespace' is a single word and always written this way in Kubernetes and OpenShift docs.  I noticed this while reviewing @arilivigni's review request for a change to support this plugin in JJB.

cc @bparees

**Comment by gabemontero** [comment]
Sure thing - will update in the near term.

**Comment by gabemontero** [comment]
addressed with https://github.com/gabemontero/openshift-jenkins-buildutils/commit/b6d0d006cbade6b5455d74e706fc1c5bec3426f8
